# Generated by Django 4.2.8 on 2023-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_user/', verbose_name='Загрузите фотографию')),
                ('name', models.CharField(max_length=100, verbose_name='Введите ФИО')),
                ('work', models.CharField(max_length=50, verbose_name='Вввдите профессию')),
                ('descriptions', models.TextField(verbose_name='Введите биографию')),
            ],
            options={
                'verbose_name': 'Информация пользователя',
                'verbose_name_plural': 'Информации пользователей',
            },
        ),
    ]
