# Generated by Django 4.2.8 on 2023-12-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awesome_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photography', models.CharField(max_length=155, verbose_name='Потрясающие услуги')),
                ('Web_Design', models.CharField(max_length=155, verbose_name='Веб-дизайн')),
                ('UI_UX_Design', models.CharField(max_length=155, verbose_name='UI-UX Дизайн')),
                ('Mobile_Apps', models.CharField(max_length=155, verbose_name='Мобильные приложения')),
            ],
            options={
                'verbose_name': 'Потрясающая услуга',
                'verbose_name_plural': 'Потрясающие услуги',
            },
        ),
    ]
