# Generated by Django 4.2.8 on 2023-12-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_awesome_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awesome_services',
            name='Mobile_Apps',
        ),
        migrations.RemoveField(
            model_name='awesome_services',
            name='Photography',
        ),
        migrations.RemoveField(
            model_name='awesome_services',
            name='UI_UX_Design',
        ),
        migrations.RemoveField(
            model_name='awesome_services',
            name='Web_Design',
        ),
        migrations.AddField(
            model_name='awesome_services',
            name='author',
            field=models.CharField(default=1, max_length=255, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awesome_services',
            name='title',
            field=models.TextField(default=1, verbose_name='Цитата'),
            preserve_default=False,
        ),
    ]
