# Generated by Django 4.2.8 on 2023-12-08 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_remove_awesome_services_mobile_apps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='awesome_services',
            options={'verbose_name': 'Цитата для главной страницы', 'verbose_name_plural': 'Цитата для главной страницы'},
        ),
    ]
