# Generated by Django 4.2.8 on 2023-12-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0005_alter_awesome_services_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Awesome_Services',
            new_name='Services',
        ),
    ]
