# Generated by Django 4.2.8 on 2023-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='descriptions3',
            field=models.TextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='title4',
            field=models.CharField(default=1, max_length=255, verbose_name='ЗАголовка-4'),
            preserve_default=False,
        ),
    ]
