# Generated by Django 4.2.8 on 2023-12-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_settings_descriptions3_settings_title4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='descriptions',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='descriptions2',
            field=models.TextField(blank=True, null=True, verbose_name='Описание2'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='descriptions3',
            field=models.TextField(blank=True, null=True, verbose_name='Описание3'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='settings', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='services_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЗАголовок - 4'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Заголовок-1'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЗАголовка-2'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЗАголовка-3'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title4',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЗАголовка-4'),
        ),
    ]
