# Generated by Django 4.2.8 on 2023-12-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0009_alter_settings_descriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='services_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ЗАголовок услуги '),
        ),
    ]
