# Generated by Django 4.2.8 on 2023-12-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0013_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Заголовка')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone', models.CharField(max_length=155, verbose_name='Телефонный номер')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка4',
            },
        ),
    ]
